### ISSUE TITLE
How to use RQ with Redis Sentinel?

### ISSUE THREAD

**Issue by sporeus** [rq/rq#1080]
I'm using Redis Sentinel and I would like to use RQ with Redis Sentinel. According to the [docs](http://python-rq.org/docs/connections/), RQ supports Sentinel and we must specify a dictionary in the configuration file. However, I don't really understand what this configuration file really is. Is there any example more specific for this usage? Please help. Thank you.

**Comment by cw1427** [comment]
Does RQ really support redis sentinel?  How about directly use redis_sentinel.master_for('mymaster') to be the connection in RQ? That means force allow RQ us redis_sentinel master node.

**Comment by vartagg** [comment]
+1

There is the only documentation about running a worker with `SENTINEL` in the settings file. But how about `Connection`, `Queue`s? How to use Sentinel as `Connection` for `Queue`?

**Comment by neiljdo** [comment]
I maybe late to the party but to I found that you can just set `REDIS_URL` config to the Sentinel master URL and everything should work on the producer-side of things.

**Comment by Asrst** [comment]
Hi, @selwin .

I guess, rq is having support for sentinel. Can you please add a example on how to use sentinel in `Connection` & `Queue` ?
as @neiljdo suggested, I am using master url for connection. rq is running fine without any connection errors, but with following issue.

**Issue:**

But once in a while (1 in 20), few jobs are missing in the `FinishedJobRegistry` even though they are successfully processed by the rq workers (we are running a rq-scheduler once in 30 secs to retrieve all Finished Jobs & then do some stuff like updating to db).  

`result_ttl` parameter is set to 600 secs & we are trying to access them immediately so expiration should not be a problem here. So debug further, we tried to access those jobs from redis manually with in 600 secs & they were present in them with status updated to `success` but still they are being retrieved by `FinshedJobRegistry` class.

This issue is observed when we use master of `redis-sentinel` for connection and not occuring when connected to redis in standard alone mode. so just want to check if we need to use specific connection method/parameter to connect to `redis-sentinel` ?
