### ISSUE TITLE
Best practice for using RQ with workers that have limited resources?

### ISSUE THREAD

**Issue by trianta2** [rq/rq#1154]
In short, I'm interested in using `rq` to dispatch work to machines with GPUs. I can run multiple applications on a single GPU, so I'll instantiate multiple workers per machine. The issue is that I don't want a worker to dequeue a work item if it doesn't have capacity to run an application on its GPU.

Does `rq` naturally support this use case? I couldn't find anything out of the box. I was thinking of overriding [this class method](https://github.com/rq/rq/blob/master/rq/queue.py#L454) in a custom `Queue` class, and I'd essentially block until there was available capacity on the GPU.

I thought I'd post here before moving forward with this approach, in case there's a more natural solution, or if there's a pitfall in my solution above.

**Comment by selwin** [comment]
Yes, you can create a specific queue, for example "high-perf" and sends jobs to that specific queue. You'd then obviously configure only your high performance boxes to accept jobs from that queue.

**Comment by sjwhitmore** [comment]
@selwin, I think @trianta2 may have been asking about a different issue, one which I am also now running into.  My problem is that I have jobs that take different amount of resources.  My most common job is one that takes 12% of my GPU, but I also sometimes need to run jobs that take 50% of my GPU.  I would like to run 6 workers, so that I have the capability of running the job that takes 12% of my GPU in parallel.  However, if I need to schedule one of the high-memory jobs, now 50% of my GPU memory is gone.  I still have 5 other workers that may accept jobs, and I do not want them to accept jobs that push them over 100% of memory!

What I have working now is what you implied in your response -- I have two GPUs, one with 6 workers and a "small" queue, and one with 2 workers and a "large" queue.  *BUT*, this is wasteful, because I don't have very many "large" jobs, and I don't want to pay for one of my GPUs to be sitting around and not doing anything.  So I would really like some sort of resource management system that would help me implement what I described above -- where I can specify some sort of "job size" and the management system automatically deals with distributing or putting a hold on the requested task if there's not enough resources.

@trianta2 I'm curious what you ended up with, if this describes your issue as well.

Thanks!

**Comment by selwin** [comment]
@sjwhitmore thanks for the clarification. I'll reopen this issue.

I don't have any short term solutions for this, but here are my thoughts on possible implementations:

1. How do we provide hooks so that you can determine whether a job should be executed? Your "job size" idea sounds interesting.

2. Dealing with this from the `Queue` side. Blocking and waiting for resource availability when enqueueing is probably not a good solution

3. Dealing with this from the `Worker` side. Workers dequeue jobs and checks for resource availability. If there's insufficient resources, put jobs back into queue, but this is inelegant and will lead to dequeue - enqueue loops while waiting for resources.

4. Dealing with this from the `Scheduler` side. I think this makes more sense, as it's the scheduler's job to decide when certain jobs should be run. Currently scheduling only works based on time and not other things like resource availability.

**Comment by sjwhitmore** [comment]
Thanks for your thoughts @selwin! I like the idea of working this into the Scheduler. I took a look at both the new version of RQScheduler included in rq and also the external rq-scheduler library.  I think my extension only fits in the external library.  My rough and somewhat hacky idea for implementation:
1) Make a queue for each resource. Register the queues along with a notion of total resource size, in an arbitrary unit (e.g. if my smallest job size is 1/6 of the total resource, then the total resource size could be 6.
2) Add a function schedule_job_by_size to the scheduler that accepts a Job.  Structure the Job ID with some notion of size e.g. "<random_string>_size_1". The function will store the Job and the time the job was added (for prioritization) in Redis.
3) Add a function get_jobs_to_queue_by_size that returns the list of jobs in Redis, ordered by time added.
4) Add a function enqueue_jobs_by_size that iterates through the jobs to queue, and finally
5) Add enqueue_job_by_size that checks the current status of all of the resource queues by adding together the units used (reading them by checking the job IDs in the queue and summing the units) and adds the job where it fits based on its own size or puts it back in the scheduler if there's no room.

I'm not sure this would work with the new included RQScheduler since I would need to select the queue for scheduling ahead of time, and thus I wouldn't be able to partition queues by resources, and would have no other way of identifying which workers are running on which resources.  Let me know what you think of this implementation idea.

**Comment by trianta2** [comment]
Right, @selwin didn't quite answer my original question, but since others didn't seem to be interested in my feature request, I didn't press the matter.

@sjtbham it sounds like our problems are similar, but mine may have been simpler, as each unit of work required the same amount of resources.

I ended up rolling my own solution in which all my GPU workers with available resources attempted to acquire an NFS file lock, and popped an item of work from a directory. It was a hack but worked well for my purposes.

**Comment by cristianprice** [comment]
@trianta2 instead of nfs file lock, use a redis lock. should be superior in all aspects.

**Comment by danielbraun89** [comment]
@sjwhitmore I need this exact solution
I will even go as far as to say it deserves to be its own Github project and product. Redis based resource allocation.

**Comment by SamsTheGreatest** [comment]
@trianta2 we have a single GPU and need to run multiple workers on in with ML models specific to each worker. I was looking into solutions for this but haven't seen any examples. Could you perhaps share an example of how you have achieved this?

**Comment by trianta2** [comment]
@SamsTheGreatest I didn't use `rq` for my project. The gist was that every VM with gpu(s) had a single worker process which would periodically check GPU resources using `nvidia-smi`, and if there were sufficient resources, the worker would pop an item of work from a queue. Each work item was a JSON file which described the task (e.g. which dataset to use, model hyperparameters, etc.). The worker would start a new process for each work item, and go back to the dequeue loop.

In hindsight, using a redis lock like @cristianprice suggested would have been better.

**Comment by lowercase00** [comment]
Would a combination of multiple queue and multiple workers make sense?

> I have two GPUs, one with 6 workers and a "small" queue, and one with 2 workers and a "large" queue. BUT, this is wasteful, because I don't have very many "large" jobs, and I don't want to pay for one of my GPUs to be sitting around and not doing anything.

`worker large` would have the `large` queue as first priority, and `small` queue second, that way it would always favor `large`, but would still be available for the `small` queue. `worker small` would only listen the to the `small` queue.

Another option is a have a loop running, workers in burst, and some more complex logic to decide whether resources are enough for the worker to actually work can also be an option:

```
w = Worker(...)
should_work = check_resources() # should I work?
if should_work:
    w.work(burst=True)
```

Closing.
