### ISSUE TITLE
Is there a way to implement 'Lazy Apps' after worker fork() a process to init Flask app

### ISSUE THREAD

**Issue by cw1427** [rq/rq#1165]
As we known as default rq worker will run the job by fork() which would share the process stack in sub process. But there are some inappropriate shared inilization actions like DB connection seccsion inilization. So is there a way in rq worker to implement like uWsgi 'Lazy Apps' or 'post fork' mechanism after worker fork() a process to init respective Flask app to isolate the context?

**Comment by selwin** [comment]
There are a few ways to do this. Django-RQ, for example [resets db connections](https://github.com/rq/django-rq/blob/master/django_rq/management/commands/rqworker.py#L90
) before running the worker so that each worker will open a new connection post fork().

You can also use a custom worker class to open DB connections before job is executed. [worker.perform_job()](https://github.com/rq/rq/blob/master/rq/worker.py#L815) is a good place for this, for example:
```python
def perform_job(self, *args, **kwargs):
    # Setup context here...
    super().perform_job(self, *args, **kwargs)
```

This should probably be documented more clearly, I'm also open to creating new pre/post execution hooks so this can be done more easily.

**Comment by cw1427** [comment]
Hi @selwin :

Thanks for the answer, Yes it works well. I refer to the django-rq way to implement a reset db connection function as below:

`def reset_db_connections():
    "similar with django-rq to shut down any opened db connection before work fork."
    ab = current_app.extensions['appbuilder']
    ab.get_session.close_all()
`
