### ISSUE TITLE
Implementing a minimal RQ in javascript

### ISSUE THREAD

**Issue by hrbonz** [rq/rq#1353]
I'm working on a project where I need to create charts based on D3.js out of a python pipeline. I've looked at running js inside python but feel like a cleaner approach would be to have the python service talk to a nodejs service through a job queue system.
I found an implementation of celery in js but feel like the added complexity is probably not worth it.

What would be a minimal set of features to implement to get a functional RQ client in js with JSON serialization?

**Comment by selwin** [comment]
Instead of recreating RQ in JS, it would be easier for you to process the job in Python, store the result somewhere else and pass it along to your JS service to be processed further.

Making an RQ worker in JS would require you to reimplement [worker.py](https://github.com/rq/rq/blob/master/rq/worker.py) in JS.
