### ISSUE TITLE
Stop a running job using job_id or job instance

### ISSUE THREAD

**Issue by AbhilashJN** [rq/rq#1371]
I have a situation where I need to cancel/stop multiple jobs and clear the job data from redis based on job_id, irrespective of whether the jobs are queued/running/completed. From the documentation, it appears that there is no way to do so, as job.cancel() and job.delete() only affect enqueued jobs. Is it possible to make job.cancel() stop a job (maybe by killing the worker horse process) if the method is called on a job which is currently running?

I'm using version 1.5.2

**Comment by codyflynnNC** [comment]
You can do that via the registry. 

http://python-rq.org/docs/job_registries/#removing-jobs

**Comment by selwin** [comment]
This is something I plan on making easier in future versions.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1376

**Comment by anton-daneyko-ultramarin** [comment]
@selwin Is there a way to not just kill the process, but do something meaningful on shutdown? My worker is interacting with the external world and I would like to shut it down gracefully: it should issue some requests first and wait for their completion.

I peeked into the implementation and it seems it would be possible to add a command along the "kill-horse" command and instead of calling `worker.kill_horse()` in `rq.command.handle_kill_worker_command` call it with some other signal. In combination with the signal handler in the worker it would be possible to initiate some graceful cancel.

WDYT?
