### ISSUE TITLE
cannot pickle '_thread.lock' object when passing Redis connection object into job function

### ISSUE THREAD

**Issue by stelmath** [rq/rq#1413]
Hello there, I trying out Python rq with a Flask app and I want to pass the Redis connection object to my job function. A very simplified example would be:

In `jobs.py`:
```Python
def send_to_redis(redis_conn):
    redis_conn.set('name', 'my_name')
```

In `app.py`:
```Python
from rq import Queue
import redis
from flask import Flask
from . import jobs

app = Flask(__name__)
redis_conn = redis.Redis(decode_responses=True)
mt_queue = Queue(connection=redis_conn)

@app.route('/')
def index():
    job = mt_queue.enqueue(jobs.send_to_redis, redis_conn)
    return 'ok'

if __name__ == '__main__':
    app.run()
```

When running the Flask app I get: `TypeError: cannot pickle '_thread.lock' object` because I am passing the redis connection to the job function. What is the proper way of doing that? (Using Python 3.8.5 in a conda environment)

Edit:
I could simply change `jobs.py` into:
```Python
import redis

def send_to_redis():
    redis_conn = redis.Redis(decode_responses=True)
    redis_conn.set('name', 'my_name')
```
and then not pass the connection object when enqueuing:  `job = mt_queue.enqueue(jobs.send_to_redis)`. But is this the proper way? Thanks!

**Comment by selwin** [comment]
Recent versions of Python can't pickle Redis instances. So you'd need to pass Redis' connection params instead of the instances into RQ.

**Comment by deduble** [comment]
> Recent versions of Python can't pickle Redis instances. So you'd need to pass Redis' connection params instead of the instances into RQ.

can you eloborate on that please? How do you pass params to RQ?

**Comment by AlexGhanem** [comment]
I am having a very similar problem with using Redis-py queues to retrieve DBs that take too long to download. I believe this was closed prematurely as I cannot find a fix anywhere. and @selwin has not explained how to implement this fix.

**Comment by deduble** [comment]
To elaborate on the issue a bit more, when you pass info about jobs/params to jobs etc., they are need to be saved to Redis, and they are saved by being pickled by design, so that a separate process, remote/local etc., can know what is the job and do it without the knowledge of what brought that job there. This basing thing was something is not written in rq. However, thread objects are not pickalable (like Queues). If you know a bit more about threading that it makes zero sense to save the thread in Redis. However your connection details are saved in Redis. 

`q = Queue("some_queue_name")`

Will refer to the same queue/will have access to same jobs, wherever you use it if you access the same redis server and their database. 
I think the issue with RQ right now is it trying to save something unimportant about queue to redis, hence failing. So try to create any RQ objects inside the tasks themselves and instead pass the more primitive arguments.

**Comment by mabreuortega** [comment]
I'm seeing this issue with Redis mlflow model

**Comment by selwin** [comment]
This is because Python can’t pickle a Redis object

**Comment by mabreuortega** [comment]
> This is because Python can’t pickle a Redis object

Do you know a workaround for the issue?

**Comment by kyutcho** [comment]
Any workaround for this yet? Trying to log LangChain Redis retriever but no luck
