### ISSUE TITLE
Jobs not requed on worker termination

### ISSUE THREAD

**Issue by levkk** [rq/rq#1461]
If the worker is terminated with `SIGTERM` or any other signal, the job it was running is not re-queued and becomes lost. This is analogous to not having SuperFetch in Sidekiq.

**Comment by selwin** [comment]
To fix this, when expired jobs are being cleaned up, it needs to be requeued if retry is set. PR to fix this is welcome.

**Comment by extremoburo** [comment]
Hello, I'm looking for the same. @selwin would your tip work also if you need to requeue a job instantly and to it will be consumed by another worker ? Thks

**Comment by extremoburo** [comment]
I had a look at the registry clean up function and it looks easy to check if retry is set and reque. @levkk are you working on this PR, If not I could try with it. 

About my issue, I'm wandering if it could make sense in order to be able to reque a job as soon as possibile (in my case jobs could take long times and expiration is too far to manage it this way) to check the `job.last_heartbeat `to realize the job is still active or crashed for any reason, if it's not refreshed for a while it means some dramma happened and so it could be moved away from the `StartedJobRegistry` and requed. Could that make sense to you ?
