### ISSUE TITLE
Succeeded jobs mysteriously moved to FailedJobRegistry

### ISSUE THREAD

**Issue by waldner** [rq/rq#1507]
Once in a while I get jobs that completed successfully moved to FailedJobRegistry.
The job terminates correctly, as shown in the logs:

```
16:44:39 default: Job OK (5a33fdd2-54bf-466a-9c6c-5aea8c37be76)
16:44:39 Result is kept for 600 seconds
```

But then after a while I see the job has been moved to FailedJobRegistry. Looking at the queues with rq-dashboard, I see this terse message:

```
Moved to FailedJobRegistry at 2021-07-04 16:46:12.479190
```
But nothing else (don't even know where rq-dashboard gets that message from). No other information in the logs. As I said, this happens only for a minority of jobs, but it does happen.
If it helps, it happened both with rq 1.8.1 and rq 1.9.0.
Could it be a failure in the rq<->redis communication so the successful termination of the job isn't properly written to redis? Looking at the rq code, I see that the move happens in `StartedJobRegistry.cleanup()` in `rq/registry.py`. From what I understand, rq thinks that the job is "expired" (based on redis score) so moves it to the failed registry.

**Comment by adamsenn** [comment]
We are also regularly seeing this issue now as well. We are on **rq 1.9**, using it with

- Django 3.2
- django-rq 2.4, and
- django-rq-scheduler@79a6c7a26b482302f3ee73467b97572f0c31effa.
 
We have similar setup in multiple other projects, but have only noticed this issue in 2 projects thus far. Unfortunately, we have not been able to nail down a reproducible case yet. While it appears your fail occurred ~90sec after your success, ours seem to consistently be in 6-7min range (3-4min jobs with 900sec timeout, ttl = None), FWIW.

**Comment by adamsenn** [comment]
We are seeing this **very frequently** now in a new project we are working on. I strongly suspect the issue is somewhere in https://github.com/rq/rq/blob/master/rq/worker.py#L982-L1006. As @waldner said, the StartedJobRegistry's `.cleanup()` function seems to be finding our successfully finished jobs stuck inside it. Using django-rq, we have seen finished jobs stuck in the StartedJobRegistry for a time, until they are eventually expired to the FailedJobRegistry:

![image](https://user-images.githubusercontent.com/32107702/128757745-117d5ee7-2e3c-4b4b-b63f-cee85ec04b24.png)

Apparently, worker.py Ln 996 successfully sets the job's status to `JobStatus.FINISHED`, but the `started_job_registry.remove()` isn't successful. Perhaps that has something to do with the fact that **we are using custom job ids?**

https://github.com/rq/rq/blob/master/rq/registry.py#L73-L75

We've tried to track this further, but unfortunately are not Redis experts and don't fully understand all that rq is doing with that. Hopefully this is useful information!

**Comment by waldner** [comment]
FWIW, I'm *not* using custom job IDs.

**Comment by selwin** [comment]
@waldner @adamsenn sorry for the late reply, I don't think it's anything to do with custom job IDs. I'll try to look into this, but it's not easy because I don't have jobs that are incorrectly moved to FailedJobRegistry.

Are you able to spot trends in jobs that are incorrectly failed? Like they take a long time to finish or something like that.

**Comment by selwin** [comment]
One more thing, are you both able to verify that these jobs are completed successfully? If they are, I can narrow down the scope of my search.

**Comment by selwin** [comment]
I added some logging statements in https://github.com/rq/rq/pull/1544 . Do you mind running RQ with debug logging turned on so we can see what's happening?

**Comment by waldner** [comment]
For my part, I can confirm that the jobs are successful (or at least the logs say so), as I showed in my original message. I'll apply the debug patch and let you know what I see. Thanks!

**Comment by waldner** [comment]
I don't see the added log messages in the log, I see that they are emitted with `self.log.debug`. Since I do see messages emitted with `self.log.info`, I suspect I have to enable some option to increase the verbosity of the logs, but I don't find anything relevant in the docs. Any help?

**Comment by waldner** [comment]
Ok, here is the log for one of those successful jobs which are moved to FailedJobRegistry:

```
19:19:53 default: myjob(foo=20107, bar='XXXX') (95995224-58fd-4e9a-af06-4cae9589e781)
... (removed) messages from the job doing its thing....
19:21:54 Handling successful execution of job 95995224-58fd-4e9a-af06-4cae9589e781
19:21:54 Setting job 95995224-58fd-4e9a-af06-4cae9589e781 status to finished
19:21:54 Removing job 95995224-58fd-4e9a-af06-4cae9589e781 from StartedJobRegistry
19:21:54 Finished handling successful execution of job 95995224-58fd-4e9a-af06-4cae9589e781
19:21:54 default: Job OK (95995224-58fd-4e9a-af06-4cae9589e781)
```

Yet it's moved to FailedJobRegistry later:

```
Moved to FailedJobRegistry at 2021-08-21 17:23:26.722741
```
I notice now that the timestamp above seems to be in UTC (it's really 19:23:26.722741). Yet the workers have their timezone set correctly, as the timestamps in the log messages show (and a simple `date` in a shell inside the worker container also confirms that). Don't know if it's related, but it just caught my attention.

**Comment by adamsenn** [comment]
I can also confirm that the jobs definitely succeed first as we have multiple indicators (including logs) that are all showing success.

**Comment by selwin** [comment]
Ok, this is super weird, from your logs we can clearly see that the job was removed from `StartedJobRegistry` and yet it was `Moved to FailedJobRegistry` again about 90 seconds later.

We know that the job has to be moved to `FailedJobRegistry` from `StartedJobRegistry` because the text `Moved to FailedJobRegistry` only appears in [StartedJobRegistry.cleanup()](https://github.com/rq/rq/blob/f9ddf7dca5b4e0182d86a9d6397502f6e460517b/rq/registry.py#L151).

Something is definitely weird here. May I know what redis-server version both of you are running @waldner @adamsenn ?

**Comment by adamsenn** [comment]
We are using AWS ElastiCache Redis 5.0.6 with Version 3.5.3 of the Python redis client.

**Comment by waldner** [comment]
redis 6.0.5-alpine in a Docker container.

**Comment by selwin** [comment]
After reading the code multiple times, I think the most probable explanation is that the `pipeline.execute()` call [here](https://github.com/rq/rq/blob/master/rq/worker.py#L1010) fails silently.

@waldner can you check if jobs that were erroneously added to `FailedJobRegistry` have `job.ended_at` value set? This value should be persisted to Redis in the same pipeline call.

**Comment by waldner** [comment]
Yes they indeed have the `ended_at` set, along with `started_at`, `created_at`, `enqueued_at`. Again, I see thise are all GMT times.

**Comment by selwin** [comment]
> Again, I see that in redis these are all GMT times.

@waldner this is by design. Because the queue and workers may be hosted on different servers, it makes sense to store all timestamps internally in UTC. They could then be converted to local timestamps when displayed to be read by humans.

I added some more debug logging statements in this branch: https://github.com/rq/rq/tree/logging-additions . Can you run this commit and see what it shows us? This is the diff of the commit: https://github.com/rq/rq/commit/c0dd5f7c982f881c561e0ab5b3ba7f57e67d0ca8

It logs two things:
1. The result of `pipeline.execute()` when the key is supposedly removed from Redis
2. Logging of `StartedJobRegistry` cleanup process when it finds keys that have expired and move them to `FailedJobRegistry`

**Comment by waldner** [comment]
Ok, here goes:

```
13:33:10 default: myjob(foo=20107, bar='XXXX') (e1e813a3-bf6a-4585-8a01-50bb8841a188)
... (removed) messages from the job doing its thing....
13:34:10 Handling successful execution of job e1e813a3-bf6a-4585-8a01-50bb8841a188
13:34:10 Setting job e1e813a3-bf6a-4585-8a01-50bb8841a188 status to finished
13:34:10 Removing job e1e813a3-bf6a-4585-8a01-50bb8841a188 from StartedJobRegistry
13:34:10 Finished handling successful execution of job e1e813a3-bf6a-4585-8a01-50bb8841a188. Redis returns [0, 1, 113, 4325.734237, 0, 0, 1, True, False, False, 1]
13:34:10 default: Job OK (e1e813a3-bf6a-4585-8a01-50bb8841a188)
13:34:10 Result is kept for 600 seconds
```

Strangely, I don't see any instance of the `registry.py` log messages (`Moving job(s) to FailedJobRegistry` and `Cleaning up StartedJobRegistry for queue`), do I have to do anything special to enable them?

**Comment by selwin** [comment]
Ok, let's take a look at this line:
```
12:46:04 Finished handling successful execution of job 2c67d796-9169-4b6f-ac9e-0902b378bb4e. Redis returns [0, 1, 24, 1476.257723, 0, 0, 1, True, False, False, 1]
```
The last result `1` is the [result of ZREM call](https://github.com/rq/rq/blob/e8ec07ed617b972c948b7554ec8287dec7444f3c/rq/registry.py#L75) that's initiated by [started_job_registry.remove()](https://github.com/rq/rq/blob/e8ec07ed617b972c948b7554ec8287dec7444f3c/rq/worker.py#L1008). `1` [means](https://redis.io/commands/zrem#return-value) Redis successfully removed 1 key from the sorted set, which means that key has been removed from `StartedJobRegistry`.

This means that since the key is already removed from `StartedJobRegistry`, it shouldn't have this key to cleanup and move to `FailedJobRegistry`. The fact that this key is still there means it's reintroduced again later, which could be due to a race condition.

I added an [extra commit](https://github.com/rq/rq/commit/c43b7fd298f9a782dcff55b1beb0335f510696d8) to check if my suspicion is True. Could you try my latest patch? If this works, I'll work on a more permanent fix.

**Comment by waldner** [comment]
So this has been running for a few hours now, and so far I see exactly zero successful jobs moved to FailedJobRegistry (earlier there would already have been some). I'll leave it running overnight and see. Great work! Thanks!

**Comment by selwin** [comment]
Great! If it stays that way, I’ll work on a more permanent fix and may need
your help to verify the fix again (hopefully just once).

**Comment by selwin** [comment]
@waldner [this branch](https://github.com/rq/rq/tree/fix-started-job-registry-race-condition) contains the permanent fix. Could you please test this out and see whether it works for you?

**Comment by waldner** [comment]
Yes! It ran all night and no job moved to FailedJobRegistry. I can say that the problem is fixed. I'll test the new branch and let you know.

**Comment by waldner** [comment]
I'm sorry but I have to report that the `fix-started-job-registry-race-condition` branch reintroduces the problem of jobs moved to `FailedJobRegistry`. I've been running it for just about two hours and I've already seen 4 such jobs. This seems to be happening at a lower rate than before, but nonetheless it's happening.
Furthermore, I now see that job parallelism seems to be greatly reduced for some reason. For this particular task, I have 40 workers set aside, and I used to see all 40 running at the same time (by looking at how many jobs were in the `StartedJobRegistry`). Now the number continuously changes, but it never gets past 30 or 32 (and it's often lower, around 20/25).

**Comment by selwin** [comment]
Ok, in that case can you try running [this fix](https://github.com/rq/rq/tree/fix-race-condition)? I'm trying to do this without incurring an additional Redis command. If this also fails, we can fallback to the quick fix.

**Comment by waldner** [comment]
This is working! Parallelism restored and no jobs moved to `FailedJobRegistry`. Thanks! Will you include the fix in a release?

**Comment by selwin** [comment]
Yes. Thanks for testing.

**Comment by adamsenn** [comment]
Great work @selwin and @waldner!

**Comment by waldner** [comment]
@adamsenn I hope it solves the issue for you too!

**Comment by waldner** [comment]
1.10.0 definitely solves this for me. Closing.

**Comment by rfrancois** [comment]
I just tried what is written in the documentation https://python-rq.org/docs/#job-callbacks with v1.11.1 and I have the same error you described.
