### ISSUE TITLE
Async job camm

### ISSUE THREAD

**Issue by RamonGiovane** [rq/rq#1697]

**Comment by RamonGiovane** [comment]
Now I don't know if the problem is with job.enqueue or with SimpleWorker.work().

I already tried `Queue('test_queue', is_async=False)`

**Comment by lowercase00** [comment]
I think this is a side effect of how async is implemented. Related to [this discussion](https://github.com/rq/rq/pull/1405).
I imagine checking for an existing loop should solve this. I'm not sure how this ended up with more than one loop running with the SimpleWorker though

**Comment by lowercase00** [comment]
@RamonGiovane I don't know your exact setup, but some experiments:
```python
# tasks.py
import asyncio

async def async_job_sample(some_param: str):
    print('Async RQ test: The param is: ' + some_param)
    await asyncio.sleep(0.2)
    print('Async RQ test: Done')
    return some_param
```

```python
# app.py
import asyncio
from redis import Redis
from rq import Queue
from app.tasks import async_job_sample

async def testing_rq():
    queue = Queue(connection=Redis())
    job = queue.enqueue(async_job_sample, 'Async test string')
    return job

job = asyncio.run(testing_rq())
```
In one terminal window `rq worker` and in the other `python3 -m app.app.py` works.
If I use the simple worker with burst, I have an error `RuntimeWarning: coroutine 'async_job_sample' was never awaited`.
If I use `async=False` I also get a `RuntimeWarning.....`

The current implementation for the job execution checks for a `coroutine` in here:

```python
# rq.job # L869
def _execute(self):
    result = self.func(*self.args, **self.kwargs)
    if asyncio.iscoroutine(result):
        loop = asyncio.new_event_loop()
        coro_result = loop.run_until_complete(result)
        return coro_result
    return result
```
I imagine that you are within a context where you already have a running loop, you may try to run with `asyncio.run(...)` as well.
I'm guessing the issue here is that the current implementation won't account for async functions being executed outside the worker (with the `worker.work` in burst mode, or the `async=False` option)?

**Comment by RamonGiovane** [comment]
Yes. Thanks for the answer. Maybe the issue title is a bit misleading. 😅

I was running some async tests using [Ward](https://ward.readthedocs.io/en/latest/)  test framework (I omitted that in the snippet I provided, thought it was irrelevant to the issue).

I don't know how they use `asyncio` under the covers but reasonable that when I run the tests, a new loop is created by Ward.

I'm new to RQ and I'm looking forward to use async jobs. I might just drop the unit tests for a while and just try with a real worker.

**Comment by lowercase00** [comment]
I have a similar case, although I use a real worker (even for testing - I use `pytest` w/ asyncio plugin).
What I *think* is happening is: `ward` runs a `asyncio.run(...)` as the entry point. This creates a new loop. When you call the function from an async context, the `run_until_complete` in the `execute` method only waits for the "top-level" (for lack of a better word) loop, so it indeed doesn't wait for the target function. Normally I guess `loop.run_until_complete` should be used within a sync context, so it's far from being bullet prof on a async context.

For example, if we switch the `run_until_complete` to `asyncio.gather(result)` we get the result alright, but we also get a `asyncio.CancelledError` since I imagine you gather the `result` from the target function, but not from your context (the asyncio function that enqueued the job itself). But again, I'm really not sure. This is mixing sync/async which is a pain in a any scenario tbh.

**Comment by pawciobiel** [comment]
IMO It would be nice to either add workaround for tests (async context) or at least mention this in docs.

@ccrvlh are you planning to open PR for thiss https://github.com/rq/rq/pull/1405#issuecomment-1217104556 
Did that work OK for your tests?
