### ISSUE TITLE
Double-run of scheduled job

### ISSUE THREAD

**Issue by veejar** [rq/rq#1831]
10 workers are running for the same queue.
When I changed code from **enqueue_in** to **enqueue** I started getting in logs double-run of the same scheduled job (job id in log was the same, start time too). Very rare issue, but definitely something is wrong in pulling scheduled job. I can't replicate it manually using some tests for now.

**Comment by lowercase00** [comment]
@veejar are you running from the CLI with `rq worker ...` or programmatically with `w.work(...)`?
Are you using 1.13? Tried downgrading to 1.12 to check whether it solves the issue?

**Comment by veejar** [comment]
@lowercase00 I'm using 1.13. The same issue I had with 1.12.
Worker started using "rq worker" command in docker container, used supervisord to run 10 worker processes.

**Comment by lowercase00** [comment]
@veejar looking at the source, this is very weird indeed: `enqueue_in` is only a wrapper on top of `enqueue_at`, it's basically just a way to pass a `timedelta` object instead of a `datetime`. Can you point to any other change that may have happened in the meantime?

```python
    def enqueue_in(self, time_delta: timedelta, func: 'FunctionReferenceType', *args, **kwargs) -> 'Job':
        """Schedules a job to be executed in a given `timedelta` object

        Args:
            time_delta (timedelta): The timedelta object
            func (FunctionReferenceType): The function reference

        Returns:
            job (Job): The enqueued Job
        """
        return self.enqueue_at(datetime.now(timezone.utc) + time_delta, func, *args, **kwargs)

```

It does seem to have something wrong with the scheduler / scheduled jobs - there's a recent comment in issue https://github.com/rq/rq/issues/1754#issuecomment-1437861349 about that as well (although the effects are entirely different, it also points to something wrong with this logic).

Keep us posted if you can replicate this in anyway, we'll try to find something with the scheduler logic.

**Comment by lowercase00** [comment]
@veejar you're running 10 worker processes within the same container? I'm not particularly familiar with supervisord, so I wonder if this is related to supervisord config rather than `rq`, so far couldn't replicate it. Can you try running 10 containers with a single worker in each one of them, please?

**Comment by veejar** [comment]
@lowercase00 sorry, my first message in this thread had mistake: **enqueue_in** was replaced with **enqueue**, not with **enqueue_at** (updated first message). So, was used regular "enqueue" instead of scheduling. I think issue is not related to workers, supervisord etc., because current version of code works good, no jobs duplicate issues. Looks like need to check RQ-src code, when Job is moved by scheduler from scheduled registry to main queue registry. Duplicate issue was very rare, need days to replicate. I think I will have ability to replicate this issue one more time soon.
One more information about my job. It has "retry" option:
`@job("high, result_ttl='1d', retry=Retry(max=3, interval=[5, 10, 30]), connection=conn)`

**Comment by lowercase00** [comment]
`enqueue_in` enqueues using the scheduler, so you need to scheduler to run it. When you use `Retry` you also need to scheduler running. Both `enqueue` and `@job` enqueues things normally (basically just a `enqueue_call` - so in both of those cases the issue wouldn't be when scheduling the jobs.

I'm not sure how supervisor handles multiple process in the context of the scheduler running in a different process itself (using `multiprocessing`), that's something that might be worth looking at. My suggestion is to try to make things simple to replicate this - remove supervisor, run one worker per container, and then check whether you can replicate anything.

I'll close this for now since it's very actionable at the moment, please feel free to reopen (or open a new issue), if you can identity anything strange and we can continue to look at it.

**Comment by KePeng1019** [comment]
> @lowercase00 sorry, my first message in this thread had mistake: **enqueue_in** was replaced with **enqueue**, not with **enqueue_at** (updated first message). So, was used regular "enqueue" instead of scheduling. I think issue is not related to workers, supervisord etc., because current version of code works good, no jobs duplicate issues. Looks like need to check RQ-src code, when Job is moved by scheduler from scheduled registry to main queue registry. Duplicate issue was very rare, need days to replicate. I think I will have ability to replicate this issue one more time soon. One more information about my job. It has "retry" option: `@job("high, result_ttl='1d', retry=Retry(max=3, interval=[5, 10, 30]), connection=conn)`

hello, how you fix this issue. I have this issue and one job is pick up by two worker in the same time.
