### ISSUE TITLE
#1729 breaks usage on Windows

### ISSUE THREAD

**Issue by viaregio** [rq/rq#1848]
#1729 introduced the following line:

`import resource`

So on windows a `ModuleNotFoundError` is raised. So even the recommended use of SimpleWorker on windows isn't possible anymore.

**Comment by lowercase00** [comment]
It seems that's because `waitpid` was replaced by `wait4`, and `struct_rusage` is being used for type annotations. If I'm not mistaken none of the code involved (the method that uses `wait4`, which is not supported on Windows) is being used by the `SimpleWorker`, so perhaps protecting this with a `try/expect` block and within a `if TYPE_CHECKING` would be enough, some testing is needed.

**Comment by lowercase00** [comment]
@viaregio could you try #1852 to see if it fixes Windows, please?
Thanks!
