### ISSUE TITLE
how to have a queue across two (or more) workers but still runs functions in sequence?

### ISSUE THREAD

**Issue by blacksteel1288** [rq/rq#1992]
Hi all,

Is there a way to have a queue that exists in multiple workers, but functions for that queue still execute in sequence instead of parallel?

For example, if I have a `worker.py` that starts 3 queues:

```
worker = SimpleWorker(['q1', 'q2', 'q3'], connection=redis)
worker.work()
```

Then, I start two of those worker processes (call them worker1, worker2):

```
python -m worker &
python -m worker &
```

The default behavior if I add long-running functions to 'q1', will be to add them to 'worker1' then 'worker2' so they run in parallel, which is not what I want.

So, currently doing:

```
q = Queue('q1', connection=redis)
job = q.enqueue(my_func_1)
q = Queue('q1', connection=redis)
job = q.enqueue(my_func_2)
q = Queue('q2', connection=redis)
job = q.enqueue(my_func_3)
```

puts `my_func_1` in worker1 and `my_func_2` in worker2 at the same time, while `my_func_3` which is for 'q2', is blocked, and must wait to start until one of the others finish.

```
my_func_1 --> q1 --> worker1
my_func_2 --> q1 --> worker2
my_func_3 --> q2 --> wait
```

What I want is for `my_func_1` for 'q1' to start in worker1, `my_func_2` to wait since it is in 'q1', and have `my_func_3` which is for 'q2' to start immediately in worker2.

```
my_func_1 --> q1 --> worker1
my_func_2 --> q1 --> wait
my_func_3 --> q2 --> worker2
```

Is this possible?

I've tried using multiprocessing to see if that would work instead of starting multiple worker processes, but I can't get the process to start multiple workers, and I am not sure if that is a good solution.

My use case is to have queues for each customer, so they could run on any worker for parallelization, but the functions for a given customer must run in sequence.

Thank you!

**Comment by hector-baez** [comment]
I accomplished a behavior similar to this by queuing the second job at the end of the first job. i.e. I run a bash script as my first job and at the end of the script I added some logic to enqueue a new job depending on the outputs that were just created.

**Comment by blacksteel1288** [comment]
I ended up doing something similar to that, where I read the contents of the queue to see what jobs are running or scheduled, then add the new job to depend_on the last job in that list.

I was hoping to find a more elegant solution, though.

My code looks something like this:


```
        queue = 'the selected queue'
        job_id = 'some string'
        q = Queue(queue, connection=redis)
        from rq.registry import StartedJobRegistry, DeferredJobRegistry
        running_jobs = StartedJobRegistry(queue, connection=redis).get_job_ids()
        deferred_jobs = DeferredJobRegistry(queue, connection=redis).get_job_ids()
        with app.app_context():
            if len(deferred_jobs) > 0:
                last_job = deferred_jobs[-1]
                job = q.enqueue(f=args[0], job_timeout='1h', job_id=job_id, args=args[1:], depends_on=last_job)
            elif len(running_jobs) > 0:
                last_job = running_jobs[-1]
                job = q.enqueue(f=args[0], job_timeout='1h', job_id=job_id, args=args[1:], depends_on=last_job)
            else:
                job = q.enqueue(f=args[0], job_timeout='1h', job_id=job_id, args=args[1:])
```

**Comment by darren-recentive** [comment]
It sounds like you're using Queue as individualistic rather than a collection
The q1, q2, q3 is better phrased as high-prioritiy-queue, medium-priority-queue, low-priority-queue
Which is why you're seeing the behaviour regarding job/function ordering

Given your use case, I would take a look at `Queue(redis_queue_namespace_prefix: str)`. This would allow you to create a queue per customer to allow for non-overlapping Jobs.
https://github.com/rq/rq/blob/a8209391fffe3bad195264e6ed22724e36ae1fb5/rq/queue.py#L69C1-L69C52

```python
customer_foo: 'foo'
customer_bar: 'bar'
foo_q = Queue(['q1', 'q2', 'q3'], connection=redis, redis_queue_namespace_prefix=f'redis:queue:{customer_foo}:')
bar_q = Queue(['q1', 'q2', 'q3'], connection=redis, redis_queue_namespace_prefix=f'redis:queue:{customer_bar}:')
foo_q.enqueue(my_func_1)
bar_q.enqueue(my_func_1)
foo_q.enqueue(my_func_1)
```

Depending how you manage your workers, that might not be feasible.
Whether or not it is, If you aren't using dependencies already, I would recommend it.
https://github.com/rq/rq/blob/a8209391fffe3bad195264e6ed22724e36ae1fb5/rq/job.py#L1537
There seems to be some code that allows for dependencies to be `enqueued_at_front` that could solve your problem
https://github.com/rq/rq/blob/a8209391fffe3bad195264e6ed22724e36ae1fb5/rq/job.py#L67

Good luck!
