### ISSUE TITLE
Custom job IDs containing `:` are no longer supported after migrating to rq 2.0 version

### ISSUE THREAD

**Issue by Marishka17** [rq/rq#2151]
The [`parse_job_id`](https://github.com/rq/rq/blob/a07b23b821bf536eaae54c7f7e7a112aaa709f62/rq/job.py#L64C5-L64C17) function introduced in RQ version 2.0 breaks support for jobs with custom IDs containing `:`. If there are no plans to continue supporting such custom IDs, this should be clearly mentioned in the documentation.

For instance:
```python
queue = Queue('queue_name', connection=connection)
queue.enqueue_call(func, job_id='job:1')
worker = Worker(queue)
assert worker.work(burst=True)
```

**Comment by SpecLad** [comment]
> If there are no plans to continue supporting such custom IDs, this should be clearly mentioned in the documentation.

I would also add that in this case RQ should also not allow jobs with such IDs to be submitted.

**Comment by gabriels1234** [comment]
I too feel that the abrupt upgrade from v1 to v2 is hurting the rq ecosystem (especially django's). I understand that a major version change implies breaking changes, but it's a big ask for the ecosystem to catch up with such short notice. There should be a way (or a plug-in) that provides full compatibility with v1.

People start new projects every day and they don't want to start with an old version of a package.

@selwin, Let us know how we can help.

**Comment by selwin** [comment]
> I understand that a major version change implies breaking changes, but it's a big ask for the ecosystem to catch up with such short notice.
RQ usually provides deprecation warnings year in advance. In this case, it slipped my mind that people may use `:` in job IDs. This is fixed in https://github.com/rq/rq/pull/2138 . I'll try to release it to PyPI soon.

> There should be a way (or a plug-in) that provides full compatibility with v1.
I typically don't see this even on projects with much bigger funding, userbase and developer ecosystem, so given that I'm mostly working on this alone, I don't think this is something I can afford to do. People release major version changes for a reason :).

> @selwin, Let us know how we can help.
A standalone RQ dashboard would be a nice project to start. This is something that I've always wanted to have but never had the time to do. Ideally, something you can install in a few lines, configure and get running right away.

**Comment by selwin** [comment]
RQ 2.1 is now on PyPI and contains the fix https://github.com/rq/rq/pull/2138
