### ISSUE TITLE
Allow job to requeue itself

### ISSUE THREAD

**Issue by jchia** [rq/rq#271]
I think it would be helpful to allow a job to requeue itself while it is running, so that it does not get removed but instead gets added to the end of the queue it came from.

One use case is a job that checks the conditions for it to do its real work. If the conditions are not right, it gets requeued to be retried later. This effect could be achieved by enqueueing a new job, but would not work if the job has dependents.

Currently, `requeue()` only applies to failed jobs, after they have failed and been put in the `failed` queue.

**Comment by dfrankow** [comment]
"One use case is a job that checks the conditions for it to do its real work. If the conditions are not right, it gets requeued to be retried later."

"This would be very useful for tasks that need to be retried due to external failures as well (for example MTA transient errors, push notification failure)."

+1

I have a worker that has external dependencies that are sometimes flaky. When the external dependency is not available, I want this worker to refuse jobs for awhile.

However, I don't want it to exit, because circus (like supervisor) would just restart the job, so it would flap.

If I made a patch to allow a job to be refused/requeued without "failing", would you accept it?

Alternate suggestions?

**Comment by selwin** [comment]
> One use case is a job that checks the conditions for it to do its real work. If the conditions are not right, it gets requeued to be retried later.

For this to work, we'd need to have a job scheduling mechanism. You can already do this via [rq-scheduler](https://github.com/rq/rq-scheduler). I'm also working on bringing scheduling mechanism into RQ's core. You can see the progress of my work in the [job-scheduling branch](https://github.com/rq/rq/tree/job-scheduling).

> However, I don't want it to exit, because circus (like supervisor) would just restart the job, so it would flap.

You can do `rq worker suspend` and `rq worker resume` to temporarily stop workers from processing the queue. However, RQ's suspension mechanism has its shortcomings when applied to [less than busy queues](https://github.com/rq/rq/issues/526).

**Comment by selwin** [comment]
> If I made a patch to allow a job to be refused/requeued without "failing", would you accept it?

I think allowing a job to be requeued when it fails is a feature that we should have. I would accept a PR for that.

The other one would be a PR to allow `job.requeue()` to be used not only on failed jobs. There could be cases when you want to requeue a finished job simply because you want to repeat the task. I'd accept a PR for this as well.

**Comment by kastolars** [comment]
Has this been implemented or is there a working example of a custom exception handler that does this? I've also tried subclassing the Worker class to handle successes depending on job metadata but that hasn't proven to be very fruitful so far.

**Comment by selwin** [comment]
Yes, job retries are already supported. https://python-rq.org/docs/exceptions/
