### ISSUE TITLE
Job status not updated if worker dies

### ISSUE THREAD

**Issue by rvernica** [rq/rq#756]
While a job is running, I do a cold shut down of the worker. The job status is still `started` even after `timeout` expired.

On the other hand, the job is marked as failed once the worker is restarted.

Here is the version info:
```python
>>> redis.__version__
'2.10.5'
>>> rq.__version__
u'0.6.0'
```

**Comment by selwin** [comment]
At the moment we don't have a separate process to run maintenance works (i.e harvesting failed jobs). Your jobs are marked as failed when one of your workers calls `worker.clean_registries()` this behavior is expected.

I'm open to adding a separate script that's dedicated to performing maintenance tasks so these tasks can be offloaded from the workers.

**Comment by proofit404** [comment]
What is the role of this script exactly? Multiple processes makes startup and shutdown proc relationship overcomplicated.

**Comment by rvernica** [comment]
I see. My use case is that I want to check the status of the jobs every once in a while. So I do `Job.fetch(job_id).get_status()`. If all the workers are gone, the job will show as `started` forever.

Now, instead of a script (which I agree it might complicate things), `Job.refresh(self)` could check if the `timeout` of the job expired and update the job status right there. `fetch` calls `refresh` already so it could work for this use case.

**Comment by selwin** [comment]
@proofit404 this script just runs queue compaction, checking for failed jobs periodically so @rvernica doesn't see the weird condition that he saw :). I don't think this is a high priority item though.

**Comment by proofit404** [comment]
The main reason I dislike separate scripts is complexity to the end user. They are easy to write, but hard to use. When you extract part of your logic into separate script you increase chances to broke process which relies on this logic. User can forgot to run this script. Script can run in not appropriate moment. All crazy stuff can happens when we split things into different processes communicating somehow.

The best option to fix this issue in my opinion is extend `should_run_maintenance_tasks` branch in the `Worker.work` method.

**Comment by selwin** [comment]
@proofit404 this issue discusses about zombie detection and immediately moving their jobs to the failed queue: https://github.com/nvie/rq/issues/787 . The proposed fixed in that issue should also address @rvernica's problem.

PR for this is welcome :)

**Comment by selwin** [comment]
Newer versions of RQ already automatically detects and moves zombie jobs to `FailedJobRegistry` after they timeout.
