### ISSUE TITLE
Adding periodic timeout (or heartbeat) to jobs

### ISSUE THREAD

**Issue by davechallis** [rq/rq#824]
I had a go at implementing #805, but after some investigation, it looks like that doesn't solve the problem I was aiming to fix.

Main aim is to allow for very long running jobs which do work in smaller chunks. Ideally, I'd like to have an overall job timeout (which might be something like 24 hours), and work chunk timeout (which might be something like 30 seconds).

This would allow for much quicker notification of any issues (e.g. worker dying, job getting stuck, etc.), without having to wait the full 24 hours.

Currently, when a job timeout is set, this results in the worker TTL being increased to at least this value, and also sets up `UnixSignalDeathPenalty` to send a `signal.alarm` if the timeout is reached.

To add the functionality I'd want, I think the following changes would be needed, just wanted to get some feedback before coding them and making a PR:

1. Modify `UnixSignalDeathPenalty` to take both `timeout` and `periodic_timeout` arguments (both optional)
2. Add `periodic_timeout` argument to `Job`
3. Set up the `UnixSignalDeathPenalty` from within `Job` rather than `Worker` when a job is started (means that jobs can cancel/update this, and workers can still access this from their reference to a job)
4. If `timeout` is set, and `periodic_timeout` is not set, everything behaves as it does now
5. If `periodic_timeout` is set, `UnixSignalDeathPenalty` uses `signal.alarm(self.periodic_timeout)`
6. Add a `heartbeat()` method to Job, which can be called by running jobs to indicate the everything is still progressing, and work is being done. This method would a) ensure that `worker.heartbeat()` is called, and b) the current UnixSignalDeathPenalty alarm is cancelled, and a new one set

Any feedback/suggestions would be welcome - there are a fair few changes here, and if they're not suitable, happy to rethink!

**Comment by selwin** [comment]
The gist of the problem is that the worker does not periodically check whether it's horse is still alive. For long running jobs like yours, it would take a long time before horse failure is detected.

At the moment, when a worker is performing a job, it just waits for its horse to finish or `UnixSignalDeathPenalty` to be fired. We should modify `_monitor_work_horse_tick ` https://github.com/nvie/rq/blob/master/rq/worker.py#L559 to periodically check (maybe every 30 seconds) whether its horse is still alive.

Apart from that, if you want to monitor your job's progress, you could periodically update `job.meta`  as you see fit.

What do you think?

**Comment by davechallis** [comment]
Yup, I think you've summed up the problem perfectly, thanks for taking a look.

Checking whether the work horse is alive periodically makes sense, will take a look into that next time I get a chance to spend some time on it.

I'm currently using the other approach you suggested - my jobs update `job.meta` with `progress` and `last_updated` fields, then I've got an external process that monitors for these stalling (which deals with stuck tasks, but not stale worker metadata yet).
