### ISSUE TITLE
Exception when using Elasticache Redis instance

### ISSUE THREAD

**Issue by j-bennet** [rq/rq#883]
We're trying to use `rq` pointing at the Redis instance in AWS Elasticache. Whenever it fails over from master to replica node (and back), we see this in logs:

```
Error 111 connecting to XXX.use1.cache.amazonaws.com:6379. Connection refused.
```

Then, enqueueing any jobs fails.

How can we handle this? Is there a "good practice" for using RQ + Elasticache?

**Comment by theodesp** [comment]
Rq uses redis-py for handling the Redis connections based on a URL. Maybe you can find more information there
https://github.com/andymccurdy/redis-py

Are you sure you are pointing to the right hostname and port?

**Comment by j-bennet** [comment]
@theodesp Yes. The initial connection succeeds, and works fine for a long time. Problems only appear during the failover.

**Comment by theodesp** [comment]
I think this is related to #862

**Comment by codywilbourn** [comment]
I believe it's a similar issue (the initially identified master may not be the master for a given key when trying to save it), but I don't know if the two issues would be resolved in the same manner. Redis cluster shards the keys out to multiple nodes, this is strictly a master/slave failover.

In Amazon's Elasticache, the cluster DNS address is actually a `CNAME` to the current master. This DNS record will change to point to the `A` record reflecting the new master upon promotion.

1. Connect to `example.use1.cache.amazonaws.com`. The CNAME is resolved to the current primary, such as `example-001.use1.cache.amazonaws.com`. The `example-001` record is an `A` record to the IP address.
2. Write data as normal
3. A failover begins. The `example-001` is demoted, and `example-002` is promoted. During this time 001 may not accept traffic, which is why rq starts getting ECONNREFUSED (error 111).
4. A failover is complete.`example.use1.cache.amazonaws.com` is now a CNAME to `example-002.use1.cache.amazonaws.com`. Writes to 001 will be rejected since it is not master if you managed to successfully reconnect.

The problem I believe is that the `connection` object tries to retry operations to the originally resolved IP address, found in step 1. Instead, the original DNS needs re-resolved to pick up the change in DNS reflecting the new master node. I don't know if this can be managed with the existing redis-py object or if it needs re-created to force a new DNS resolution.

**Comment by theodesp** [comment]
As I see it, it might be more of a routing issue among other things.

The thing is that all critical components (Queue, Registry, Job) initiate a Redis connection using the 
`resolve_connection` function which attempts to connect using the redis.py library
https://github.com/nvie/rq/blob/fa6c28bf3c6cf171279eab83e6b17183bf0f1c2d/rq/connections.py#L61

If that succeeds then a TCP connection is established and kept in memory. This is the one and only way that redis.py resolves a DNS query as seen here:

https://github.com/andymccurdy/redis-py/blob/8a186ebd9cecf466624803bdf215030158c7c776/redis/connection.py#L510-L511

Which means that in order for the original DNS needs re-resolved **all the connections first need to close and then be reestablished** which I think goes out of the scope of the project right now.

What I mean let's say for example the RQ connections, are sending TCP packets destined to a fixed IP address xxx.xxx.xxx.xxx should and may not have to deal with anything else than Redis Protocol requests and responses which means that a middleware between RQ and the redis server should pick up the failover state and while is in progress  make a note to the routing table to forward the packets destined to that original IP address to the `example-002` node.

I think this is a more viable solution, for this, something like a reverse proxy or a service mesh that will pick up the changes and make sure the packets are destined to the right server.

**Comment by selwin** [comment]
This is not an issue with RQ itself. Closing.
