### ISSUE TITLE
How to make RQ faster between multiple processes?

### ISSUE THREAD

**Issue by kivo360** [rq/rq#935]
Hi RQ Community!

My team and I are creating an infrastructure using multiple steps within Redis RQ. We're using Redis RQ to process information at multiple steps without blocking Kafka consumers. One think I notice is that the code is move pretty darn slow. Like 3-4 seconds between 4 jobs for each task. Assuming we have 200 jobs going through our system each minute, I want to make sure we're able to handle all of the tasks we receive. I would like some pointers on how we can handle all of the tasks:

Some things I've thought of, yet haven't tried:
* Use PyPy to speed some of the workers up.
* Use multiple workers for some tasks.
* Place parts of code into separate functions into Cython to speed some tasks.

Is it possible for me to use Gevent Workers? I see it in the document, but I didn't see it anywhere else. Do we have to create Gevent Workers?

**Comment by samuelcolvin** [comment]
Gevent is very old news. Asyncio is the way forward. 

Where's the load? CPU or io?

What's the overhead for running a job? Eg how many no op jobs can your system process per minute?

If the bottle neck is CPU cython might help. 

If the bottle neck is io, asyncio is your friend (either via lots of concurrent tasks in rq or a complete trunk using arq, arq is faster anyway as it's preforked).

Otherwise check you don't have some silly bottleneck due to a network perform or trace condition.

**Comment by kivo360** [comment]
How do I make my workers use asyncio?

**Comment by samuelcolvin** [comment]
You can run a coroutine inside a job as normal. 

Otherwise for a fully async approach look at https://github.com/samuelcolvin/arq.

**Comment by samuelcolvin** [comment]
Closing this as it's not an issue with rq.
