### ISSUE TITLE
Same Job Picked Up by All Workers

### ISSUE THREAD

**Issue by jaakkopasanen** [rq/rq#994]
I have three workers running in a Docker swarm with one Redis container and a container running the process which creates the jobs. Normally this works fine but recently I had an issue where a job was picked up by all three workers. I have been running two workers, Redis and the process which creates the tasks on a same machine for a long time and have never had any problems. I suspect this might have to do with all of them running in separate containers on multiple docker swarm hosts.

Does RQ have any kind of locking mechanism for the queue so that first worker would block other workers from taking the same job?

**Comment by olingerc** [comment]
I had the same problem when I tried to implement the multi-deprndencies feature. I hope we csn find a solution. The would highly increase my motivation to pick it up again.

**Comment by selwin** [comment]
RQ uses `blpop` to pickup enqueued jobs. Even if you're running three workers, `redis.blpop()` guarantees that each job is only popped once so I'm not sure how that's possible.

I'd look into how your docker swarm hosts are configured and whether you're running additional worker/job processing logic which may lead to such an issue.

If you find any evidence that this is caused by a bug in RQ, please reopen this issue.

**Comment by lgg42** [comment]
Hi @jaakkopasanen, did you ever find a solution? I ran into the exactly same problem... this is my docker containers stdout..
```
scraper-worker_3          | 23:00:02 free: updates.update_single_db_item(68) (161a46a9-37d4-44e5-9eef-13a3fd96eb58)
scraper-worker_2          | 23:00:02 free: updates.update_single_db_item(68) (161a46a9-37d4-44e5-9eef-13a3fd96eb58)
```
using **rq 1.7.0**
